### ISSUE TITLE
Suggestion: if .gitattributes has an override with linguist-language=UNKNOWN, then add it with a new random color to code line stats anyway

### ISSUE THREAD

**Issue by ell1e** [dayvonjersen/linguist#7]
I have the following suggestion which would be really great to have on [gitea](https://gitea.io) which at least from my googling uses this library: it would be great if when a repo's `.gitattributes` file contains an override with linguist-language=UNKNOWN (as in the language isn't known to linguist) if then that language would be added with the given name `UNKNOWN` and any choice of unused color to the statistics such that it shows up on gitea's stats bar. This would be a really great addition for creators of small languages that have repos on gitea instances without admin access to allow them to mark their source files such that the overall repo stats are correct, even though that obviously still won't fix the missing syntax highlighting.

Please note the original linguist does currently **not** support this and unknown languages set via the `.gitattributes` file will be ignored right now on GitHub. But there is apparently no good reasoning for this other than <insert buy-in, product manager, marketing words, ...>(?) as you can see here: https://github.com/github/linguist/issues/4435#issuecomment-617554362

So maybe it would be worth adding to this fork-alike where there is no weird backroom talk needed to get it done?

**Comment by dayvonjersen** [comment]
Hi thanks for your suggestion :)

I really don't remember how this thing works or how to code in general anymore, does what you're asking have anything to do with this: https://github.com/dayvonjersen/linguist/pull/5 ?

If not or "sort of but not really", I'd be glad to add/change whatever needs doing. It will probably take me some time to get around to it myself, so it might be more expeditious if you wanted to try to tackle it yourself and I could merge it or whatever

**Comment by ell1e** [comment]
Well currently, `.gitattributes` overrides can only use languages that *exist*. Others are dropped in the final stats, this is both the case on GitHub and gitea right now (the latter which is using this go linguist project here).

This feature request is basically "keep made up languages in .gitattributes in the final stats." If that leaves any associated properties like the color for the bar (if that is also configured in go linguist) missing then just pick any color e.g. based on a name hash, randomness, or whatever.

**Comment by dayvonjersen** [comment]
Ah, I understand now. I believe this would do that as it doesn't appear to cross-check the linguist-language specified against anything: https://github.com/dayvonjersen/linguist/compare/feature/gitattributes

I guess I never merged it because I expected to merge #5 once it was working ...

**If something is reading a .gitattributes file it isn't using this library currently.**

I know you said you were trying to avoid taking this issue over to @gitea but they're quite nice from what I remember. I don't know if they're using this library; I remember I made a language bar prototype for gogs which got rejected and someone at gitea saw it and wanted to add that feature, and I know that they did eventually but I honestly don't know if they used any of my code or designs. 

Unfortunately, you're gonna have to take this up with them because even if I do add this feature (and I think I will, thank you sincerely for making me aware of it) I don't think it will solve your problem there :\

-day

**Comment by ell1e** [comment]
@dayvonjersen thanks so much for finding this out! I made a gitea ticket now: https://github.com/go-gitea/gitea/issues/14528

**Comment by ell1e** [comment]
Closing this since gitea implemented this now! :tada:
